DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS review_likes;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS film_genre;
DROP TABLE IF EXISTS film;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS mpaa_rating;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS "user";

-- 1. Создаем таблицу для рейтингов MPAA
CREATE TABLE mpaa_rating (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(10) NOT NULL UNIQUE,
    description TEXT
);

-- 2. Создаем таблицу жанров
CREATE TABLE genre (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

-- 3. Создаем таблицу фильмов
CREATE TABLE film (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    release_date DATE,
    duration INT, -- Длительность в минутах
    mpaa_rating_id INT NOT NULL, --
    CONSTRAINT fk_mpaa_rating FOREIGN KEY (mpaa_rating_id) REFERENCES mpaa_rating (id) ON DELETE RESTRICT
);

-- 4. Создаем связующую таблицу
CREATE TABLE film_genre (
    film_id INT,
    genre_id INT,
    -- Установка внешних ключей с каскадным удалением
    CONSTRAINT fk_film FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE,
    CONSTRAINT fk_genre FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE RESTRICT,
    -- Составной первичный ключ гарантирует уникальность пары film_id и genre_id
    CONSTRAINT pk_film_genre PRIMARY KEY (film_id, genre_id)
);

-- Создаем таблицу пользователей
CREATE TABLE "user" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100),
    birthday DATE,
    CONSTRAINT uk_user_login UNIQUE (login)
);

-- Создаем таблицу дружбы (связующая таблица)
CREATE TABLE friends (
    user1_id INT REFERENCES "user"(id) ON DELETE CASCADE,
    user2_id INT REFERENCES "user"(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL,
    PRIMARY KEY (user1_id, user2_id) -- составной первичный ключ, чтобы избежать дублей пар
);

CREATE TABLE likes (
    user_id INT REFERENCES "user"(id) ON DELETE CASCADE,
    film_id INT REFERENCES film(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, film_id)
);

CREATE TABLE reviews (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     TEXT        NOT NULL,
    is_positive BOOLEAN     NOT NULL,
    user_id     INT         NOT NULL,
    film_id     INT         NOT NULL,
    useful      INT         NOT NULL DEFAULT 0,
    CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT fk_review_film FOREIGN KEY (film_id) REFERENCES film(id) ON DELETE CASCADE
);

CREATE TABLE review_likes (
    review_id INT     NOT NULL,
    user_id   INT     NOT NULL,
    is_like   BOOLEAN NOT NULL,  -- true = like (+1), false = dislike (-1)
    CONSTRAINT pk_review_likes PRIMARY KEY (review_id, user_id),
    CONSTRAINT fk_rl_review FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,
    CONSTRAINT fk_rl_user   FOREIGN KEY (user_id)   REFERENCES "user"(id) ON DELETE CASCADE
);