DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS film_genre;
DROP TABLE IF EXISTS film;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS mpaa_rating;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS "user";

-- 1. Создаем таблицу для рейтингов MPAA
CREATE TABLE mpaa_rating (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(10) NOT NULL UNIQUE,
    description TEXT
);

-- 2. Создаем таблицу жанров
CREATE TABLE genre (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

-- 3. Создаем таблицу фильмов
CREATE TABLE film (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    release_date DATE,
    duration INT, -- Длительность в минутах
    mpaa_rating_id INT NOT NULL, --
    CONSTRAINT fk_mpaa_rating FOREIGN KEY (mpaa_rating_id) REFERENCES mpaa_rating (id) ON DELETE RESTRICT
);

-- 4. Создаем связующую таблицу
CREATE TABLE film_genre (
    film_id INT,
    genre_id INT,
    -- Установка внешних ключей с каскадным удалением
    CONSTRAINT fk_film FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE,
    CONSTRAINT fk_genre FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE RESTRICT,
    -- Составной первичный ключ гарантирует уникальность пары film_id и genre_id
    CONSTRAINT pk_film_genre PRIMARY KEY (film_id, genre_id)
);

-- Создаем таблицу пользователей
CREATE TABLE "user" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100),
    birthday DATE
);

-- Создаем таблицу дружбы (связующая таблица)
CREATE TABLE friends (
    user1_id INT REFERENCES "user"(id) ON DELETE CASCADE,
    user2_id INT REFERENCES "user"(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL,
    PRIMARY KEY (user1_id, user2_id) -- составной первичный ключ, чтобы избежать дублей пар
);

CREATE TABLE likes (
    user_id INT REFERENCES "user"(id) ON DELETE CASCADE,
    film_id INT REFERENCES film(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, film_id)
);